# Generated by Django 5.1.1 on 2024-10-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Case_4', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
