# Generated by Django 5.1.1 on 2024-10-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Case_4', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id_membro', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('cargo', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
