# Generated by Django 5.1.1 on 2024-10-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Case_4', '0003_membro_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('preco', models.IntegerField()),
                ('dias', models.IntegerField()),
                ('coordenadores', models.TextField()),
                ('projetistas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id_trainee', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('curso', models.TextField(max_length=255)),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sistema',
        ),
    ]
