# Generated by Django 5.1.1 on 2024-10-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Case_4', '0004_projeto_trainee_delete_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='idade',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='semestre',
            field=models.TextField(max_length=255),
        ),
    ]
