# Generated by Django 5.1.1 on 2024-10-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Case_4', '0006_membro_projetos_alter_projeto_coordenadores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id_meta', models.AutoField(primary_key=True, serialize=False)),
                ('meta', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='membro',
            name='projetos',
            field=models.JSONField(default=list),
        ),
    ]
